apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "backend.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default 8080 }}
      nodePort: {{ .Values.service.nodePort }}