services:
  backend:
    build:
      context: ./backend
    image: store-api
    container_name: my-store
    ports:
      - "8080:8080"

  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.9.3
    container_name: promtail
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail.yaml

  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    ports:
      - "3200:3200"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin