name: Run Jenkinsfile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch to run on'
        required: true
        default: 'main'

jobs:
  jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.7
        with:
          ref: ${{ github.event.inputs.branch || github.ref }}
      - name: Run Jenkinsfile Runner
        uses: jenkinsci/jfr-static-image-action@master
        with:
          jenkinsfile: Jenkinsfile
          pluginsfile: plugin.txt
        working-directory: jenkins
