name: Run Jenkinsfile

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  jenkins:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./jenkins
    steps:
      - name: Checkout code
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.7
        with:
          ref: ${{ github.ref }}
      - name: Run Jenkinsfile
        uses: jenkinsci/jfr-static-image-action@master
        with:
          jenkinsfile: Jenkinsfile
          pluginstxt: jenkins/plugins.txt

